public class Constants 
{
	public static final string Unsplash = 'Unsplash';
    public static final string Pinterest = 'Pinterest';
    public static final string Einstein_Vision = 'EinsteinVision';
    
    public static final string Auth_Deploy_Success = 'Deploy_Success';
    public static final string Auth_Deploy_Failure = 'Deploy_Failure';
    
    public static final string Dataset_Created = 'Dataset_Created';
    public static final string Dataset_Accepted = 'Dataset_Accepted';
    
    public static final string Dataset_Training_Queued = 'Dataset_Training_Queued';
    public static final string Dataset_Training_Started = 'Dataset_Training_Started';
    public static final string Dataset_Training_Succeeded = 'Dataset_Training_Succeeded';
    public static final string Dataset_Training_Failed = 'Dataset_Training_Failed';
    
    public static final string Classification_Created = 'Classification_Created';
    public static final string Classification_Results = 'Classification_Results';
}