public class Constants 
{
	public static final string Unsplash = 'Unsplash';
    public static final string Pinterest = 'Pinterest';
    public static final string Einstein_Vision = 'EinsteinVision';
    
    public static final string Auth_Deploy_Success = 'Deploy_Success';
    public static final string Auth_Deploy_Failure = 'Deploy_Failure';
    
    public static final string Dataset_Create = 'Dataset_Created';
}